# TensorFlow 2 Data Type Basics

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # Reduce TF verbosity
import tensorflow as tf
tf.get_logger().setLevel('INFO') # Reduce TF verbosity
print(f"tensorflow version: {tf.__version__}")

import matplotlib.pyplot as plt
import numpy as np

tensorflow version: 2.10.0


## TensorFlow constant values

As the name suggests, constants are immutables. Variables are created using `tf.Variable`

In [2]:
# scalar value
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print('1.')
print(x)

# rank 1 tensor
y = tf.constant([1, 2, 3])
print('2.')
print(y)

# rank 2 tensor (matrix)
m = tf.constant([[1,2 ,3], [4, 5, 6]])
print('3.')
print(m)

# matrix containing ones, rank 2 tensor
ones = tf.ones((3, 3))
print('4.')
print(ones)

# identity matrix, rank 2 tensor
identity = tf.eye(3)
print('5.')
print(identity)

# matrix with random values, rank 2 tensor
rnd = tf.random.normal((2, 3), mean=1.0, stddev=0.5)
print('6.')
print(rnd)
print('-----')

# matrix with uniformly distributed values between [0...1], rank 2 tensor
uform = tf.random.uniform((2, 3), minval=0, maxval=1)
print('7.')
print(uform)

# a range of values
r = tf.range(10)
print('8.')
print(r)

1.
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
2.
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
3.
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
4.
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
5.
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
6.
tf.Tensor(
[[1.9823394  1.7859478  1.3261111 ]
 [1.1440848  0.11606419 1.2924155 ]], shape=(2, 3), dtype=float32)
-----
7.
tf.Tensor(
[[0.8398901  0.4631716  0.7548835 ]
 [0.14560199 0.8421397  0.755653  ]], shape=(2, 3), dtype=float32)
8.
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


## TensorFlow variables

TensorFlow variables should be used when the value is expected to be modified later on.

In [3]:
x = tf.Variable([1, 2, 3])
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


## Casting values

Tensors are immutable, therefore after changing the type using casting, the new tensor needs to be assigned, like so: `x = tf.cast(x, dtype=tf.float32)`

In [4]:
x = tf.range(10)
print("Before casting")
print(x)
x = tf.cast(x, dtype=tf.float32)
print("After casting")
print(x)

Before casting
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
After casting
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## Operations on tensors

All operations like +, -, * etc. are elementwise operations.

In [5]:
x = tf.constant([1, 2, 3])
y = tf.constant([2, 2, 2])
print(x*y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Dot product is carried out using `tensordot`. You need to define the direction using the axes-parameter

In [6]:
x = tf.constant([1, 2, 3])
y = tf.constant([2, 2, 2])
z = tf.tensordot(x, y, axes=1)
print(f"Dot product of [1, 2, 3] and [2, 2, 2] is {z}")

Dot product of [1, 2, 3] and [2, 2, 2] is 12


Matrix multiplication

In [7]:
x = tf.constant([1, 2, 3], shape=(1,3))
y = tf.constant([2, 2, 2], shape=(3,1))
z1 = tf.matmul(x, y)
z2 = x @ y
print(f"x = {x}")
print(f"y = {y}")
print(f"Result of tf.matmul(x, y) is {z1}")
print(f"Result of x @ y is {z2}")

x = [[1 2 3]]
y = [[2]
 [2]
 [2]]
Result of tf.matmul(x, y) is [[12]]
Result of x @ y is [[12]]


## Slicing and reshaping

Slicing works similarly to as in Numpy

In [8]:
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"x = {x}")
print(f"x[:, 0] = {x[:, 0]}")
print(x[0, 0])

x = [[1 2 3 4]
 [5 6 7 8]]
x[:, 0] = [1 5]
tf.Tensor(1, shape=(), dtype=int32)


Reshaping

In [9]:
x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Before reshaping")
print(x)
print("----------")
x = tf.reshape(x, shape=(4, 2))
print("After reshaping")
print(x)

Before reshaping
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
----------
After reshaping
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


## Convert a TensorFlow tensor into Numpy-format & convert Numpy into TensorFlow format

In [10]:
x = tf.constant([1, 2, 3])
y = x.numpy()
z = tf.convert_to_tensor(y)
print(f"type(x) is {type(x)}")
print(f"type(y) is {type(y)}")
print(f"type(z) is {type(z)}")

type(x) is <class 'tensorflow.python.framework.ops.EagerTensor'>
type(y) is <class 'numpy.ndarray'>
type(z) is <class 'tensorflow.python.framework.ops.EagerTensor'>


## Strings

In [11]:
x = tf.constant(["hubba", "bubba"])
print(x)

tf.Tensor([b'hubba' b'bubba'], shape=(2,), dtype=string)
